// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vessel/proto/vessel/vessel.proto

package vessel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Vessel struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Capacity             int32    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,3,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Available            bool     `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	OwnerId              int64    `protobuf:"varint,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vessel) Reset()         { *m = Vessel{} }
func (m *Vessel) String() string { return proto.CompactTextString(m) }
func (*Vessel) ProtoMessage()    {}
func (*Vessel) Descriptor() ([]byte, []int) {
	return fileDescriptor_e03a24ec74fcd970, []int{0}
}

func (m *Vessel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vessel.Unmarshal(m, b)
}
func (m *Vessel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vessel.Marshal(b, m, deterministic)
}
func (m *Vessel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vessel.Merge(m, src)
}
func (m *Vessel) XXX_Size() int {
	return xxx_messageInfo_Vessel.Size(m)
}
func (m *Vessel) XXX_DiscardUnknown() {
	xxx_messageInfo_Vessel.DiscardUnknown(m)
}

var xxx_messageInfo_Vessel proto.InternalMessageInfo

func (m *Vessel) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Vessel) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Vessel) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func (m *Vessel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vessel) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *Vessel) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

type Specification struct {
	Capacity             int32    `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,2,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Specification) Reset()         { *m = Specification{} }
func (m *Specification) String() string { return proto.CompactTextString(m) }
func (*Specification) ProtoMessage()    {}
func (*Specification) Descriptor() ([]byte, []int) {
	return fileDescriptor_e03a24ec74fcd970, []int{1}
}

func (m *Specification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Specification.Unmarshal(m, b)
}
func (m *Specification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Specification.Marshal(b, m, deterministic)
}
func (m *Specification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Specification.Merge(m, src)
}
func (m *Specification) XXX_Size() int {
	return xxx_messageInfo_Specification.Size(m)
}
func (m *Specification) XXX_DiscardUnknown() {
	xxx_messageInfo_Specification.DiscardUnknown(m)
}

var xxx_messageInfo_Specification proto.InternalMessageInfo

func (m *Specification) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Specification) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

type Response struct {
	Vessel               *Vessel   `protobuf:"bytes,1,opt,name=vessel,proto3" json:"vessel,omitempty"`
	Vessels              []*Vessel `protobuf:"bytes,2,rep,name=vessels,proto3" json:"vessels,omitempty"`
	Created              string    `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e03a24ec74fcd970, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetVessel() *Vessel {
	if m != nil {
		return m.Vessel
	}
	return nil
}

func (m *Response) GetVessels() []*Vessel {
	if m != nil {
		return m.Vessels
	}
	return nil
}

func (m *Response) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func init() {
	proto.RegisterType((*Vessel)(nil), "vessel.Vessel")
	proto.RegisterType((*Specification)(nil), "vessel.Specification")
	proto.RegisterType((*Response)(nil), "vessel.Response")
}

func init() { proto.RegisterFile("vessel/proto/vessel/vessel.proto", fileDescriptor_e03a24ec74fcd970) }

var fileDescriptor_e03a24ec74fcd970 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xd9, 0xb4, 0x4d, 0x93, 0xd1, 0x16, 0x19, 0x10, 0xd6, 0xa2, 0xb0, 0xf4, 0x20, 0x39,
	0xb5, 0x52, 0x2f, 0x5e, 0x55, 0x10, 0xf4, 0xb8, 0x05, 0x05, 0x2f, 0x65, 0xbb, 0x3b, 0xea, 0x42,
	0x9b, 0x84, 0x24, 0xa4, 0x15, 0xbf, 0x8c, 0x1f, 0x55, 0xd8, 0xfc, 0x91, 0xa8, 0x78, 0xca, 0xbc,
	0x37, 0x93, 0xe1, 0xb7, 0x6f, 0x40, 0x94, 0x94, 0xe7, 0xb4, 0x99, 0xa7, 0x59, 0x52, 0x24, 0xf3,
	0x5a, 0x54, 0x9f, 0x99, 0xf3, 0xd0, 0xaf, 0xd4, 0xf4, 0x93, 0x81, 0xff, 0xe8, 0x4a, 0x1c, 0x83,
	0x67, 0x0d, 0x67, 0x82, 0x45, 0x3d, 0xe9, 0x59, 0x83, 0x13, 0x08, 0xb4, 0x4a, 0x95, 0xb6, 0xc5,
	0x3b, 0xf7, 0x04, 0x8b, 0x06, 0xb2, 0xd5, 0x78, 0x06, 0xb0, 0x55, 0xfb, 0xd5, 0x8e, 0xec, 0xeb,
	0x5b, 0xc1, 0x7b, 0xae, 0x1b, 0x6e, 0xd5, 0xfe, 0xc9, 0x19, 0x88, 0xd0, 0x8f, 0xd5, 0x96, 0x78,
	0x5f, 0xb0, 0x28, 0x94, 0xae, 0xc6, 0x53, 0x08, 0x55, 0xa9, 0xec, 0x46, 0xad, 0x37, 0xc4, 0x07,
	0x82, 0x45, 0x81, 0xfc, 0x36, 0xf0, 0x04, 0x82, 0x64, 0x17, 0x53, 0xb6, 0xb2, 0x86, 0xfb, 0x0e,
	0x61, 0xe8, 0xf4, 0xbd, 0x99, 0x3e, 0xc0, 0x68, 0x99, 0x92, 0xb6, 0x2f, 0x56, 0xab, 0xc2, 0x26,
	0x71, 0x07, 0x8c, 0xfd, 0x0b, 0xe6, 0xfd, 0x00, 0x9b, 0x96, 0x10, 0x48, 0xca, 0xd3, 0x24, 0xce,
	0x09, 0xcf, 0xa1, 0x0e, 0xc1, 0x2d, 0x39, 0x58, 0x8c, 0x67, 0x75, 0x42, 0x55, 0x1e, 0xb2, 0xee,
	0x62, 0x04, 0xc3, 0xaa, 0xca, 0xb9, 0x27, 0x7a, 0x7f, 0x0c, 0x36, 0x6d, 0xe4, 0x30, 0xd4, 0x19,
	0xa9, 0x82, 0x8c, 0x8b, 0x24, 0x94, 0x8d, 0x5c, 0x7c, 0xc0, 0xa8, 0x1a, 0x5e, 0x52, 0x56, 0x5a,
	0x4d, 0x78, 0x05, 0xa3, 0x3b, 0x1b, 0x9b, 0xeb, 0x36, 0x80, 0xe3, 0x66, 0x69, 0xe7, 0xad, 0x93,
	0xa3, 0xc6, 0x6e, 0xb1, 0x2f, 0xe0, 0xf0, 0xd6, 0x6d, 0x6d, 0xce, 0xd6, 0xa5, 0xf9, 0xfd, 0xc7,
	0x0d, 0x3c, 0x07, 0xb3, 0xfa, 0xfa, 0x6b, 0xdf, 0x9d, 0xff, 0xf2, 0x2b, 0x00, 0x00, 0xff, 0xff,
	0xa5, 0xd7, 0xa2, 0x8d, 0x22, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for VesselService service

type VesselServiceClient interface {
	FindAvailable(ctx context.Context, in *Specification, opts ...client.CallOption) (*Response, error)
	CreateVessel(ctx context.Context, in *Vessel, opts ...client.CallOption) (*Response, error)
}

type vesselServiceClient struct {
	c           client.Client
	serviceName string
}

func NewVesselServiceClient(serviceName string, c client.Client) VesselServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "vessel"
	}
	return &vesselServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *vesselServiceClient) FindAvailable(ctx context.Context, in *Specification, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "VesselService.FindAvailable", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vesselServiceClient) CreateVessel(ctx context.Context, in *Vessel, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "VesselService.CreateVessel", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VesselService service

type VesselServiceHandler interface {
	FindAvailable(context.Context, *Specification, *Response) error
	CreateVessel(context.Context, *Vessel, *Response) error
}

func RegisterVesselServiceHandler(s server.Server, hdlr VesselServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&VesselService{hdlr}, opts...))
}

type VesselService struct {
	VesselServiceHandler
}

func (h *VesselService) FindAvailable(ctx context.Context, in *Specification, out *Response) error {
	return h.VesselServiceHandler.FindAvailable(ctx, in, out)
}

func (h *VesselService) CreateVessel(ctx context.Context, in *Vessel, out *Response) error {
	return h.VesselServiceHandler.CreateVessel(ctx, in, out)
}
